clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  npm-install:
    group: install
    image: node:8-alpine
    commands: ["npm install"]

  test:
    group: test
    image: node:8-alpine
    commands: ["npm test -s"]

  release:
    group: publish
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
    when:
      event: push

